import { StyleSheet } from 'react-native';
import { COLORS } from '@/src/constants/Theme';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F9F9F9' },
  scrollContent: { padding: 20, paddingBottom: 40 },
  topInfo: { alignItems: 'flex-end', marginBottom: 20 },
  mainQuestion: { fontSize: 22, fontWeight: 'bold', color: COLORS.primary },
  subQuestion: { fontSize: 13, color: '#888', marginTop: 4 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  sectionTitleGroupSpace: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 25, marginBottom: 15, justifyContent: 'flex-end' },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  rowReverse: { flexDirection: 'row-reverse', alignItems: 'center', gap: 10 },
  addButton: { backgroundColor: COLORS.primary, width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  card: { backgroundColor: '#fff', borderRadius: 16, padding: 18, marginBottom: 12, elevation: 3, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10 },
  inputLabel: { fontSize: 12, color: '#777', textAlign: 'right', marginBottom: 6 },
  input: { backgroundColor: '#F5F7F5', borderRadius: 12, padding: 12, color: '#333', textAlign: 'right', marginBottom: 10 },
  row: { flexDirection: 'row-reverse', alignItems: 'center' },
  flex1: { flex: 1 },
  itemGap: { width: 15 },
  widthInput: { marginHorizontal: 8 },
  deleteBtn: { padding: 10 },
  locationField: { flexDirection: 'row-reverse', alignItems: 'center', paddingVertical: 12, gap: 12 },
  locationText: { fontSize: 14, color: '#444', flex: 1, textAlign: 'right' },
  lineDivider: { height: 1, backgroundColor: '#F0F0F0', marginVertical: 4 },
  emptyText: { color: '#777', textAlign: 'right' },
  driverCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, padding: 15, marginBottom: 10, alignItems: 'center', borderWidth: 1, borderColor: '#EEE' },
  selectedDriverCard: { borderColor: COLORS.primary, backgroundColor: '#F1F8F1' },
  driverInfo: { flex: 1, alignItems: 'flex-end', marginRight: 15 },
  driverName: { fontWeight: 'bold', fontSize: 15 },
  driverType: { color: '#888', fontSize: 11 },
  rateText: { fontWeight: 'bold', fontSize: 14 },
  driverAvatar: { width: 40, height: 40, borderRadius: 20 },
  driverAvatarFallback: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F3F4F6' },
  checkBadge: { position: 'absolute', top: 8, left: 8 },
  submitButton: { backgroundColor: '#0A2900', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', padding: 20, borderRadius: 18, marginTop: 25, gap: 10 },
  submitButtonDisabled: { opacity: 0.7 },
  submitButtonText: { color: '#fff', fontSize: 17, fontWeight: 'bold' },
  mapContainer: { flex: 1 },
  map: { flex: 1 },
  crosshair: { position: 'absolute', top: '50%', left: '50%', marginLeft: -22, marginTop: -45 },
  mapFooter: { position: 'absolute', bottom: 40, left: 20, right: 20 },
  confirmBtn: { backgroundColor: COLORS.primary, padding: 18, borderRadius: 15, alignItems: 'center', elevation: 5 },
  confirmBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  cancelBtn: { alignItems: 'center', marginTop: 15 },
  cancelBtnText: { color: 'red' },
});

export default styles;
