import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  titleBand: {
    height: 78,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    elevation: 2,
  },
  headerText: { alignItems: 'flex-end' },
  title: { fontSize: 24, fontWeight: '900', color: '#0b3a00' },
  subtitle: { marginTop: 2, fontSize: 13, color: '#666' },
  content: { flex: 1, padding: 20, paddingBottom: 110 },
  profileCard: {
    backgroundColor: '#fff',
    borderRadius: 22,
    padding: 22,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eef0ef',
    elevation: 2,
  },
  avatarWrap: { width: 132, height: 132, position: 'relative', marginBottom: 18 },
  avatar: { width: 132, height: 132, borderRadius: 66, backgroundColor: '#eef0ef' },
  avatarFallback: {
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: '#eef9ea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraButton: {
    position: 'absolute',
    bottom: 2,
    left: 2,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#145300',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#fff',
  },
  galleryButton: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#eef9ea',
    elevation: 2,
  },
  name: { fontSize: 24, fontWeight: '900', color: '#111827', textAlign: 'center', marginBottom: 14 },
  infoRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f8f9fa',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '100%',
    justifyContent: 'center',
    marginBottom: 18,
  },
  infoText: { color: '#374151', fontSize: 14, fontWeight: '700' },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 82,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  previewImage: {
    width: '100%',
    height: '78%',
  },
  previewCloseButton: {
    position: 'absolute',
    top: 48,
    right: 24,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
});

export default styles;
