import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  scrollContent: { paddingHorizontal: 24, paddingTop: 24, paddingBottom: 130 },
  loader: { marginTop: 80 },
  statusRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  orderNumber: { alignItems: 'flex-end', gap: 4 },
  label: { color: '#41493c', fontSize: 13, fontWeight: '600' },
  orderCode: { color: '#191c1d', fontSize: 18, fontWeight: '900' },
  statusBadge: {
    backgroundColor: '#145300',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 999,
  },
  statusText: { color: '#84c769', fontSize: 12, fontWeight: '900' },
  routeCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    flexDirection: 'row-reverse',
    gap: 16,
    marginBottom: 16,
  },
  routeLine: { alignItems: 'center', paddingVertical: 4 },
  pickupDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#94d878',
    borderWidth: 4,
    borderColor: '#ecfdf5',
  },
  line: { width: 2, flex: 1, backgroundColor: '#e2e8f0', marginVertical: 5 },
  dropoffDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#0b3a00',
    borderWidth: 4,
    borderColor: '#ecfdf5',
  },
  routeContent: { flex: 1, gap: 24, alignItems: 'flex-end' },
  routeLabel: { color: '#41493c', fontSize: 12, fontWeight: '800', marginBottom: 4 },
  routeValue: { color: '#191c1d', fontSize: 16, fontWeight: '900', lineHeight: 23, textAlign: 'right' },
  infoGrid: { flexDirection: 'row-reverse', gap: 12, marginBottom: 16 },
  infoTile: {
    flex: 1,
    minHeight: 76,
    backgroundColor: '#f3f4f5',
    borderRadius: 24,
    padding: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  infoIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoText: { flex: 1, alignItems: 'flex-end' },
  infoLabel: { color: '#41493c', fontSize: 10, fontWeight: '900' },
  infoValue: { color: '#191c1d', fontSize: 13, fontWeight: '900', marginTop: 3, textAlign: 'right' },
  inventoryCard: { backgroundColor: '#fff', borderRadius: 24, padding: 24, marginBottom: 16 },
  cardTitleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  cardTitle: { color: '#191c1d', fontSize: 18, fontWeight: '900' },
  countBadge: { backgroundColor: '#ecfdf5', paddingHorizontal: 12, paddingVertical: 5, borderRadius: 999 },
  countText: { color: '#0b3a00', fontSize: 12, fontWeight: '900' },
  itemRow: {
    minHeight: 72,
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    padding: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  itemLeft: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12, flex: 1 },
  itemIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemName: { color: '#191c1d', fontSize: 15, fontWeight: '800', flex: 1, textAlign: 'right' },
  itemQuantity: { color: '#0b3a00', fontSize: 16, fontWeight: '900', marginRight: 8 },
  driverCard: {
    backgroundColor: '#0b3a00',
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  driverInfo: { flexDirection: 'row-reverse', alignItems: 'center', gap: 14, flex: 1 },
  driverImage: { width: 56, height: 56, borderRadius: 28, borderWidth: 2, borderColor: 'rgba(52, 211, 153, 0.35)' },
  driverText: { flex: 1, alignItems: 'flex-end' },
  driverEyebrow: { color: '#6ee7b7', fontSize: 10, fontWeight: '900' },
  driverName: { color: '#fff', fontSize: 18, fontWeight: '900', marginTop: 2 },
  driverVehicle: { color: 'rgba(209, 250, 229, 0.78)', fontSize: 12, marginTop: 2, textAlign: 'right' },
  driverActions: { flexDirection: 'row-reverse', gap: 8 },
  driverActionButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#065f46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomAction: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingHorizontal: 24,
    paddingTop: 18,
    paddingBottom: 28,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
  },
  trackButton: {
    height: 64,
    borderRadius: 24,
    backgroundColor: '#0b3a00',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  trackButtonText: { color: '#fff', fontSize: 18, fontWeight: '900' },
});

export default styles;
