import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  scrollContent: { padding: 20, paddingBottom: 100 },
  timerCard: {
    backgroundColor: '#ecfdf5',
    borderRadius: 20,
    padding: 18,
    marginBottom: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  timerLabel: { color: '#064e3b', fontSize: 14, fontWeight: '900' },
  timerValue: { color: '#064e3b', fontSize: 22, fontWeight: '900' },
  timerArrived: { color: '#15803d' },
  mapContainer: {
    height: 250,
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 20,
    position: 'relative',
  },
  mapImage: { width: '100%', height: '100%' },
  locationBadge: {
    position: 'absolute',
    top: 16,
    right: 16,
    left: 16,
    backgroundColor: 'rgba(255,255,255,0.9)',
    flexDirection: 'row-reverse',
    padding: 10,
    borderRadius: 50,
    alignItems: 'center',
    gap: 8,
  },
  locationText: { fontSize: 12, fontWeight: '700', color: '#064e3b' },
  focusButton: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 50,
    elevation: 5,
  },
  driverCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 20,
    elevation: 2,
  },
  driverLoader: { marginVertical: 20 },
  driverEmptyText: { textAlign: 'center', color: '#666', marginVertical: 20 },
  driverHeader: { flexDirection: 'row-reverse', alignItems: 'center', marginBottom: 20 },
  driverAvatarContainer: { position: 'relative' },
  driverImage: { width: 60, height: 60, borderRadius: 30, borderWidth: 2, borderColor: '#ecfdf5' },
  verifiedBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#064e3b',
    padding: 2,
    borderRadius: 10,
  },
  driverInfoText: { flex: 1, marginRight: 15, alignItems: 'flex-end' },
  nameRow: { flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  driverName: { fontSize: 18, fontWeight: '700', color: '#191c1d' },
  ratingBadge: { flexDirection: 'row-reverse', backgroundColor: '#ecfdf5', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 20, gap: 4 },
  ratingText: { fontSize: 12, fontWeight: '700', color: '#064e3b' },
  truckDetails: { fontSize: 13, color: '#666', marginTop: 4 },
  whatsappButton: {
    backgroundColor: '#064e3b',
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    borderRadius: 50,
    gap: 10,
  },
  whatsappText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  timelineCard: { backgroundColor: '#f3f4f5', borderRadius: 24, padding: 20 },
  timelineHeader: { flexDirection: 'row-reverse', alignItems: 'center', gap: 8, marginBottom: 25 },
  timelineTitle: { fontSize: 14, fontWeight: '700', color: '#064e3b' },
  timelineContainer: { position: 'relative', paddingRight: 30 },
  verticalLine: {
    position: 'absolute',
    right: 9,
    top: 10,
    bottom: 10,
    width: 2,
    backgroundColor: '#d1d5db',
    borderRadius: 1,
  },
  stepRow: { flexDirection: 'row-reverse', marginBottom: 35, alignItems: 'flex-start' },
  stepUpcoming: { opacity: 0.4 },
  dot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#e5e7eb',
    position: 'absolute',
    right: -30,
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dotCompleted: { backgroundColor: '#064e3b' },
  dotActive: { backgroundColor: '#064e3b', borderWidth: 4, borderColor: '#ecfdf5' },
  innerDot: { width: 6, height: 6, backgroundColor: '#fff', borderRadius: 3 },
  stepContent: { flex: 1, alignItems: 'flex-end' },
  stepTitle: { fontSize: 14, fontWeight: '700', color: '#064e3b' },
  stepSubtitle: { fontSize: 12, color: '#666', marginTop: 4, textAlign: 'right' },
});

export default styles;
