import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  titleBand: {
    height: 78,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    elevation: 2,
  },
  headerText: { alignItems: 'flex-end' },
  title: { fontSize: 24, fontWeight: '900', color: '#0b3a00' },
  subtitle: { marginTop: 2, fontSize: 13, color: '#666' },
  listContent: { padding: 20, paddingBottom: 36 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#eef0ef',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
  },
  cardContent: { flex: 1, alignItems: 'flex-end' },
  cardHeader: {
    width: '100%',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  cardTitle: { flex: 1, textAlign: 'right', color: '#111827', fontSize: 16, fontWeight: '900' },
  statusBadge: {
    backgroundColor: '#e8f7e1',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusText: { color: '#145300', fontSize: 11, fontWeight: '900' },
  cancelledBadge: { backgroundColor: '#fef2f2' },
  cancelledText: { color: '#dc2626' },
  metaRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
    marginTop: 8,
  },
  metaText: { color: '#6b7280', fontSize: 12, fontWeight: '700' },
  metaDot: { color: '#9ca3af', fontSize: 12 },
  summaryRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
  },
  summaryText: { color: '#374151', fontSize: 12, fontWeight: '800' },
  centerState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  emptyIcon: {
    width: 66,
    height: 66,
    borderRadius: 20,
    backgroundColor: '#eef0ef',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  emptyTitle: { fontSize: 18, fontWeight: '900', color: '#111827', marginBottom: 6 },
  emptyText: { fontSize: 13, color: '#6b7280', textAlign: 'center', lineHeight: 20 },
});

export default styles;
